### ISSUE TITLE
problems after seeking

### ISSUE THREAD

**Issue by olwaldi** [oscaropenness/plugin.video.ctuplinkrss#1] opened 2022-01-01 07:01 UTC
Starting with kodi matrix release (currently I'm on osmc December 2021 release) seeking within ctuplink podcasts fails. Watching videos is working fine. When one starts seeking the video is fasttforwarded as expected. But when one resumes playback with normal speed the picture is frozen (maybe sometimes the picture is updated, but some still pictures are shown) while the sound proceeds. If one then tries to resolve this by using pause/fastforward/play kodi seems to restart.

My hardware is a raspberry pi 3.

If I try the same with some videos from Arte TV channel (also using h.264/AAC) is working fine ie. seeking works as expected.

Thus I assume that something within ctuplink addon might be wrong.

Regards, Michael

**Comment by oscaropenness** [comment] 2022-01-01 09:18
Thank you for bringing this up. I cannot recall noticing this in my setup. I will try to reproduce and hopefully fix this soon.
It might have something to do with hardware/software you are using, though. I am on RPi4/LibrELEC.

**Comment by oscaropenness** [comment] 2022-01-03 12:18
I have done some testing myself and seeking and resuming playback works flawlessly in my Kodi installations (LibreELEC on RPi4, Kodi 19.3-2 on ArchLinux).

There must be something different with your setup that leads to this issue. Maybe you can provide some Logs from the crash to pin down the problem?

I will close this issue for now, but if you can provide information, what I could do to resolve this issue, I will gladly reopen it.

**Closed as completed by oscaropenness** 2022-01-03 12:18 UTC

**Comment by olwaldi** [comment] 2022-01-03 12:56
I have reproduced my problem with debugging engaged. I started some ctuplink video, started seeking with up to 32x, then continuation of playback with normal speed fails. But there was no crash. When  pressed the play button to start normal playback the download bar at the top of the window jumped back to zero instead to continue from the reached location.

[kodi.log.gz](https://github.com/oscaropenness/plugin.video.ctuplinkrss/files/7801962/kodi.log.gz)

Thanks for looking into my problem,
Michael

**Comment by oscaropenness** [comment] 2022-01-03 13:50
Thank you for the logs.

From the Error about _buffer timeout_
`2022-01-03 13:39:59.789 T:13578 WARNING <general>: OutputPicture - timeout waiting for buffer`
I suspect it has something to do with the stream hadling by InputStreamAdaptive. Maybe have a look into [this issue report](https://github.com/xbmc/xbmc/issues/19011).

Anyway, I doubt that it has something to do with my addon specifically, since it mostly uses built-in functionality from Kodi. Maybe wait for the next OSMC update for the issue to resolve.
